services:
  mongodb:
    build: .
    container_name: mongodb
    networks:
      containers:
        aliases:
          - mongodb
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      #- MONGO_INITDB_DATABASE=my-service
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017
    #expose:
    #  - 27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 10s

  pws:
      container_name: mongotest
      #build: .
      build: ./mongotest
      networks:
        containers:
          aliases:
            - mongotest
      ports:
        - 8000:8000
      restart: always
      depends_on:
        - mongodb

networks:
  containers:
    name: containers
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
