version: '3'

services:
  mongodb:
    build: .
    hostname: mongodb
    networks:
      - net
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      #- MONGO_INITDB_DATABASE=my-service
      - MONGO_REPLICA_SET_NAME=rs0
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27005:27017
    #expose:
    #  - 27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 10s

  pws:
      #build: .
      build: ./mongotest
      networks:
        - net
      ports:
        - 8000:8000
      restart: always
      depends_on:
        - mongodb

networks:
  net:
    driver: bridge

